language: go

go:
  - 1.3
  - 1.4
  - tip

install:
  - go build -v -o $HOME/gopath/src/github.com/cn/gb2260.go/cmd/generate github.com/cn/gb2260.go/cmd

script: cd ./cmd && ./generate && cd ../ && go test -v ./...
